name: Build Kernel Pro

on:
  workflow_dispatch:

jobs:
  build:
    name: Compiling Kernel
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Load Config
      run: |
        cat config.env | while read -r line || [[ -n "$line" ]]; do
          if [[ ! "$line" =~ ^# && -n "$line" ]]; then
            echo "$line" >> $GITHUB_ENV
          fi
        done

        - name: Install Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3

    - name: Fetch Clang
      run: |
        mkdir -p $GITHUB_WORKSPACE/workspace/clang
        git clone --depth=1 ${{ env.CUSTOM_CLANG_SOURCE }} -b ${{ env.CUSTOM_CLANG_BRANCH }} $GITHUB_WORKSPACE/workspace/clang

    - name: Fetch Kernel Source
      run: |
        mkdir -p $GITHUB_WORKSPACE/workspace/kernel
        git clone --depth=1 ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} $GITHUB_WORKSPACE/workspace/kernel --recursive

    - name: Inject KernelSU
      run: |
        cd $GITHUB_WORKSPACE/workspace/kernel
        curl -LSs "https://githubusercontent.com" | bash -s main

    - name: Build Magic
      run: |
        cd $GITHUB_WORKSPACE/workspace/kernel
        export ARCH=arm64
        export SUBARCH=arm64
        export PATH="$GITHUB_WORKSPACE/workspace/clang/bin:$PATH"
        
        echo "CONFIG_KPROBES=y" >> arch/arm64/configs/${{ env.KERNEL_CONFIG }}
        echo "CONFIG_HAVE_KPROBES=y" >> arch/arm64/configs/${{ env.KERNEL_CONFIG }}
        echo "CONFIG_KPROBE_EVENTS=y" >> arch/arm64/configs/${{ env.KERNEL_CONFIG }}
        echo "CONFIG_OVERLAY_FS=y" >> arch/arm64/configs/${{ env.KERNEL_CONFIG }}
        
        make O=out ${{ env.KERNEL_CONFIG }}
        make -j$(nproc --all) O=out CC=clang CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip

    - name: Upload Loot
      uses: actions/upload-artifact@v4
      with:
        name: KernelSU-POCO-M4
        path: ${{ github.workspace }}/workspace/kernel/out/arch/arm64/boot/Image.gz

